#include<iostream.h>
#include<conio.h>
void main()
{
   int a,b;
   clrscr();
   cout<<"enter n value:";
   cin>>a;
   cout<<"enter b value:";
   cin>>b;
   cout<<"\n sum of a and b values:"<<a+b;
   cout<<"\n difference of a and b values:"<<a-b;
   cout<<"\n multiplecation of and bvalues:"<<a*b;
   cout<< "\n division of a and bvalues:"<<a/b;
   cout<<"\n modules of a and b values:"<<a%b;
   getch();
   }