#include<iostream.h>
#include<conio.h>
void main()
{
   int eid;
   char ename[25];
   float sal;
   char design[20],dept[25];
   clrscr();
   cout<<"\n enter employee id:",eid;
   cout<<"\n enter employee name:",ename;
   cout<<"\n enter employee salary:",sal;
   cout<<"\n enter employee designstion:",design;
   cout<<"\n enter employee department:",dept;
   cout<<"\n ***employee details***";
   cout<<"\n employee id:";
   cin>>eid;
   cout<<"\n employee name:";
   cin>>ename;
   cout<<"\n employee salary:";
   cin>>sal;
   cout<<"\n employee designataion:";
   cin>>design;
   cout<<"\n employee department:";
   cin>>dept;
   getch();
   }
