#include<iostream.h>
#invlude<conio.h>
int sum(int,int);//function declaration
float sum(float,float);
void main()
{
   int i1,i2;
   float x1,x2;
   clrscr();
   sum(i1,i2);//function calling
   sum(x1,x2);
   getch();
}
int sum(int i1,i2)//function definition
{
cout<<"\n sum of two integer value"<<s<<endl;
return 0;
}
cout<<"\n enter float x1,float x2");
cin>>x1>>x2
float r=x1+x2
cout<<"\n sum of the float value:"
return 0;
}

