#include<iostream.h>
#include<conio.h>
void main()
{
   int rno;
   char name[25];
   float fees;
   char course[20];
   clrscr();
cout<<"\n enter roll number:",rno;
cout<<"\n enter name:",name;
cout<<"\n enter fees:",fees;
cout<<"\n enter course:",course;
cout<<"\n *** student data 1 is***";
cout<<"\n student roll number:";
cin>>rno;
cout<<"\n student name:";
cin>>name;
cout<<"\n student fees:";
cin>>fees;
cout<<"\n student course:";
cin>>course;
getch();
}
